### PR TITLE
Add Invoice Item support

### PR DESCRIPTION
**Pull request by ryanwood**
Add the ability to find, list, create, & delete invoice items. I also fixed a typo in a second commit. Let me know if you have any questions. I went ahead and bumped the version in my commit. I'm no sure if that's preferred or not. Let me know if you'd like me to remove that.

### CODE REVIEW

**Comment by OutlawAndy** [comment]
Hey Ryan.  This kicks ass, thanks!  I've been crazy busy and haven't had a chance to take a look at this just yet, but I wanted to jump in here real quick to let you know I'm not ducking this pull request, just a little backed up with work and that I really appreciate you contributing to the project!  Thanks for being patient with me!

**Comment by OutlawAndy** [comment]
Okay, couple of quick thoughts.
- code looks awesome!
- bonus points for documentation!!
- thanks for catching the typo
- the version should def be bumped, but I would say go ahead and make it **1.8.0**  I haven't always been great at this, but as a rule of thumb I try to follow [semver](http://semver.org)

Also, would you mind updating the change log?  In fact, could you make two entries in the change log?  One for the date config at **1.7.0**, and another for this feature?

let me know if you need anything or if you simply don't have time to add that stuff.

Thanks again, Ryan!

**Comment by ryanwood** [comment]
@OutlawAndy Sorry, just saw this. For some reason I never got a notification. Will do as soon as I get a chance. Thanks for the feedback.

**Comment by OutlawAndy** [comment]
@ryanwood Thanks again, Ryan.  Huge contribution, and very much appreciated.  Just pushed v1.8.0 to RubyGems

**Pull request merged**
